nginx:
  image: nginx
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /etc/nginx/certs:/etc/nginx/certs:ro
    - /etc/nginx/conf.d
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
  restart: always

nginx-gen:
  image: jwilder/docker-gen
  container_name: nginx-gen
  volumes_from:
    - nginx
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  entrypoint: /bin/sh -c
  command: ["/usr/local/bin/docker-gen -notify-sighup nginx -only-exposed -watch -wait 30s:60s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"]
  restart: always

letsencrypt:
  image: jrcs/letsencrypt-nginx-proxy-companion:latest
  container_name: letsencrypt
  environment:
    - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
  volumes_from:
    - nginx
  volumes:
    - /etc/nginx/certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
  restart: always

cdn:
  image: nginx
  environment:
    - VIRTUAL_HOST=mpcdn.guerrademitos.com
    - LETSENCRYPT_HOST=mpcdn.guerrademitos.com
    - LETSENCRYPT_EMAIL=info@guerrademitos.com
  volumes:
    - ./cdn:/usr/share/nginx/html:ro
  restart: always

app:
  image: mawpedia
  links:
    - db
  environment:
    NODE_ENV: production
    VIRTUAL_HOST: 'mawpedia.guerrademitos.com,mitopedia.guerrademitos.com'
    LETSENCRYPT_HOST: 'mawpedia.guerrademitos.com,mitopedia.guerrademitos.com'
    LETSENCRYPT_EMAIL: info@guerrademitos.com
  volumes:
    - ./cdn:/cdn
    - ./local.json:/usr/src/app/config/local.json:ro
  restart: always

db:
  image: redis:latest
  volumes:
    - ./data:/data
  command: redis-server --appendonly yes
  restart: always
